export const WORLD_W = 480
export const WORLD_H = 720
export const NET_Y = WORLD_H / 2
export const STAT_MIN = 1
export const STAT_MAX = 9
export const STAT_BUDGET = 20
export const FIXED_STEP_MS = 1000 / 60
export const MAX_FRAME_MS = 100
export const COUNTDOWN_MS = 1800
export const POINT_RESULT_MS = 1100
export const COURT_LEFT = 54
export const COURT_RIGHT = 426
export const COURT_TOP = 48
export const COURT_BOTTOM = 672
export const PLAYER_MIN_X = COURT_LEFT + 18
export const PLAYER_MAX_X = COURT_RIGHT - 18
export const PLAYER_NET_GAP = 26
export const PLAYER_BASE_SPEED = 120
export const PLAYER_SPEED_PER_STAT = 9
export const SWING_RECOVERY_BASE_MS = 430
export const SWING_RECOVERY_PER_STAT_MS = 25
export const REACH_X = 34
export const REACH_Y = 42
export const CONTACT_MIN_Z = 8
export const CONTACT_MAX_Z = 78
export const NET_HEIGHT = 30
export const GRAVITY = 410
export const BOUNCE_FACTOR = 0.62
export const SERVE_BASE_SPEED = 265
export const SERVE_SPEED_PER_STAT = 13
export const SHOT_BASE_SPEED = 240
export const SHOT_SPEED_PER_STAT = 12
